### ISSUE TITLE
Follow renames issue.

### ISSUE THREAD

**Issue by vladshablinsky** [vladshablinsky/test_follow_renames#1]
![renames_diagram](https://cloud.githubusercontent.com/assets/4408920/14502373/a86df9d0-01b3-11e6-8335-df616fe3d3fd.png)

(NOTE: the crosses on the diagram are for deletions)

I'm trying to follow renames from specific commits and can't succeed.
For example, I want to find what happens with `b.txt` after commit [`6d08daf`](https://github.com/vladshablinsky/test_follow_renames/commit/6d08dafd7bed7f6b9fe96f8ad08dd4b08fe96d6b) (the second one). As we can see from the diagram it's renamed to `c.txt` at [`67fe9b1`,](https://github.com/vladshablinsky/test_follow_renames/commit/67fe9b1fcf8dab7394c3d55fcf3dc9ae35829f9f) but

`git log --pretty=%H --reverse 6d08daf.. --follow --diff-filter=ADR --name-status -M85% -- b.txt`

 says that `b.txt` is just deleted at [`67fe9b1`](https://github.com/vladshablinsky/test_follow_renames/commit/67fe9b1fcf8dab7394c3d55fcf3dc9ae35829f9f) and produces the following output:

```
67fe9b1fcf8dab7394c3d55fcf3dc9ae35829f9f

D   b.txt
2f89c38206017ef3242cd2baee321b03261ecc4d

A   b.txt
4cca152cc81be68d7006279d682277331a9d640c

D   b.txt
ec2d4f391d94a32491370cd567962323177c557a

R098    a.txt   b.txt
f8e6df0efe11c0300fe53968edad52d5afe01306

R093    e.txt   a.txt
c1fc35a52119f7b67206dba45f273e9986fd7ced

R098    b.txt   e.txt
cd7d5cca908754bb26636ee0be1514d4cb9d326e

R092    a.txt   b.txt
a3a41e3ae098e6054eecae7ba7c670bc3e7f817f

R098    e.txt   a.txt
762f68c2199aac84a4acfa06b371d2ed2723f6b3

R092    b.txt   e.txt
```

**Comment by vladshablinsky** [comment]
cc @mikemcquaid

**Comment by MikeMcQuaid** [comment]
@vladshablinsky Sucks. It might just be easier to use the `renames.json` file or whatever you proposed previously. Sorry to lead you down this approach and thanks for running with it ❤️

**Comment by vladshablinsky** [comment]
OK, I'll get back to non-git approach then, thanks!
